<?php

namespace AppBundle\Repository;

/**
 * ContactInformationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactInformationRepository extends \Doctrine\ORM\EntityRepository
{
}
