<?php

namespace AppBundle\Repository;

/**
 * InterlocutorsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InterlocutorsRepository extends \Doctrine\ORM\EntityRepository
{
}
