<?php

namespace AppBundle\Repository;

/**
 * MailExchangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailExchangeRepository extends \Doctrine\ORM\EntityRepository
{
}
