<?php

namespace AppBundle\Repository;

/**
 * TelephoneExchangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelephoneExchangeRepository extends \Doctrine\ORM\EntityRepository
{
}
