<?php

namespace AppBundle\Repository;

/**
 * ContractStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractStatusRepository extends \Doctrine\ORM\EntityRepository
{
}
