<?php

namespace AppBundle\Repository;

/**
 * ContractPeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContractPeriodRepository extends \Doctrine\ORM\EntityRepository
{
}
