<?php

namespace AppBundle\Repository;

/**
 * ExtraLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtraLineRepository extends \Doctrine\ORM\EntityRepository
{
}
