<?php

namespace AppBundle\Repository;

/**
 * RestaurantImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantImageRepository extends \Doctrine\ORM\EntityRepository
{
}
