<?php

namespace AppBundle\Repository;

/**
 * ScheduleExceptionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleExceptionTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
