<?php

namespace AppBundle\Repository;

/**
 * ScheduleExceptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ScheduleExceptionRepository extends \Doctrine\ORM\EntityRepository
{
}
