<?php

namespace AppBundle\Repository;

/**
 * VirginContractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VirginContractRepository extends \Doctrine\ORM\EntityRepository
{
}
