<?php

namespace AdminBundle\Repository;

/**
 * AdminTokenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdminTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
